namespace SMS.REQUESTDATA.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class FKRelationshipsBreak : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.ClassAssignement", "AssignmentId", "dbo.Assignment");
            DropForeignKey("dbo.ClassAssignement", "ClassId", "dbo.Class");
            DropForeignKey("dbo.ClassStudentDiary", "ClassId", "dbo.Class");
            DropForeignKey("dbo.ClassStudentDiary", "StudentDiaryId", "dbo.StudentDiary");
            DropForeignKey("dbo.Assignment", "InstructorId", "dbo.Employee");
            DropForeignKey("dbo.Employee", "DesignationId", "dbo.Designation");
            DropForeignKey("dbo.Designation", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.EmployeeFinanceDetails", "EmployeeId", "dbo.Employee");
            DropForeignKey("dbo.Student", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Student", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.StudentAssignment", "AssignmentId", "dbo.Assignment");
            DropForeignKey("dbo.StudentAssignment", "StudentId", "dbo.Student");
            DropForeignKey("dbo.StudentFinanceDetails", "StudentId", "dbo.Student");
            DropForeignKey("dbo.StudentStudentDiary", "StudentId", "dbo.Student");
            DropForeignKey("dbo.StudentStudentDiary", "StudentDiaryId", "dbo.StudentDiary");
            DropForeignKey("dbo.Employee", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.StudentDiary", "InstructorId", "dbo.Employee");
            DropForeignKey("dbo.ClassTeacherDiary", "ClassId", "dbo.Class");
            DropForeignKey("dbo.ClassTeacherDiary", "TeacherDiaryId", "dbo.TeacherDiary");
            DropForeignKey("dbo.TeacherDiary", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.TeacherDiary", "InstructorId", "dbo.Employee");
            DropForeignKey("dbo.TimeTableDetails", "ClassId", "dbo.Class");
            DropForeignKey("dbo.Period", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.TimeTable", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.TimeTableDetails", "TeacherId", "dbo.Employee");
            DropForeignKey("dbo.Worksheet", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.Worksheet", "InstructorId", "dbo.Employee");
            DropForeignKey("dbo.StudentDiary", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.CourseClass", "ClassId", "dbo.Class");
            DropForeignKey("dbo.CourseClass", "CourseId", "dbo.Course");
            DropForeignKey("dbo.Course", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.Class", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.Assignment", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.LessonPlan", "SchoolId", "dbo.Schools");
            DropForeignKey("dbo.StudentAttendanceDetail", "StudentId", "dbo.Student");
            DropForeignKey("dbo.StudentAttendance", "ClassId", "dbo.Class");
            DropForeignKey("dbo.StudentAttendance", "SchoolId", "dbo.Schools");
            DropIndex("dbo.Assignment", new[] { "InstructorId" });
            DropIndex("dbo.Assignment", new[] { "SchoolId" });
            DropIndex("dbo.ClassAssignement", new[] { "ClassId" });
            DropIndex("dbo.ClassAssignement", new[] { "AssignmentId" });
            DropIndex("dbo.Class", new[] { "SchoolId" });
            DropIndex("dbo.ClassStudentDiary", new[] { "StudentDiaryId" });
            DropIndex("dbo.ClassStudentDiary", new[] { "ClassId" });
            DropIndex("dbo.StudentDiary", new[] { "InstructorId" });
            DropIndex("dbo.StudentDiary", new[] { "SchoolId" });
            DropIndex("dbo.Employee", new[] { "DesignationId" });
            DropIndex("dbo.Employee", new[] { "SchoolId" });
            DropIndex("dbo.Designation", new[] { "SchoolId" });
            DropIndex("dbo.EmployeeFinanceDetails", new[] { "EmployeeId" });
            DropIndex("dbo.Student", new[] { "ClassId" });
            DropIndex("dbo.Student", new[] { "SchoolId" });
            DropIndex("dbo.StudentAssignment", new[] { "StudentId" });
            DropIndex("dbo.StudentAssignment", new[] { "AssignmentId" });
            DropIndex("dbo.StudentFinanceDetails", new[] { "StudentId" });
            DropIndex("dbo.StudentStudentDiary", new[] { "StudentDiaryId" });
            DropIndex("dbo.StudentStudentDiary", new[] { "StudentId" });
            DropIndex("dbo.TeacherDiary", new[] { "InstructorId" });
            DropIndex("dbo.TeacherDiary", new[] { "SchoolId" });
            DropIndex("dbo.ClassTeacherDiary", new[] { "TeacherDiaryId" });
            DropIndex("dbo.ClassTeacherDiary", new[] { "ClassId" });
            DropIndex("dbo.TimeTableDetails", new[] { "ClassId" });
            DropIndex("dbo.TimeTableDetails", new[] { "TeacherId" });
            DropIndex("dbo.Period", new[] { "SchoolId" });
            DropIndex("dbo.TimeTable", new[] { "SchoolId" });
            DropIndex("dbo.Worksheet", new[] { "InstructorId" });
            DropIndex("dbo.Worksheet", new[] { "SchoolId" });
            DropIndex("dbo.CourseClass", new[] { "CourseId" });
            DropIndex("dbo.CourseClass", new[] { "ClassId" });
            DropIndex("dbo.Course", new[] { "SchoolId" });
            DropIndex("dbo.LessonPlan", new[] { "SchoolId" });
            DropIndex("dbo.StudentAttendanceDetail", new[] { "StudentId" });
            DropIndex("dbo.StudentAttendance", new[] { "SchoolId" });
            DropIndex("dbo.StudentAttendance", new[] { "ClassId" });
        }
        
        public override void Down()
        {
            CreateIndex("dbo.StudentAttendance", "ClassId");
            CreateIndex("dbo.StudentAttendance", "SchoolId");
            CreateIndex("dbo.StudentAttendanceDetail", "StudentId");
            CreateIndex("dbo.LessonPlan", "SchoolId");
            CreateIndex("dbo.Course", "SchoolId");
            CreateIndex("dbo.CourseClass", "ClassId");
            CreateIndex("dbo.CourseClass", "CourseId");
            CreateIndex("dbo.Worksheet", "SchoolId");
            CreateIndex("dbo.Worksheet", "InstructorId");
            CreateIndex("dbo.TimeTable", "SchoolId");
            CreateIndex("dbo.Period", "SchoolId");
            CreateIndex("dbo.TimeTableDetails", "TeacherId");
            CreateIndex("dbo.TimeTableDetails", "ClassId");
            CreateIndex("dbo.ClassTeacherDiary", "ClassId");
            CreateIndex("dbo.ClassTeacherDiary", "TeacherDiaryId");
            CreateIndex("dbo.TeacherDiary", "SchoolId");
            CreateIndex("dbo.TeacherDiary", "InstructorId");
            CreateIndex("dbo.StudentStudentDiary", "StudentId");
            CreateIndex("dbo.StudentStudentDiary", "StudentDiaryId");
            CreateIndex("dbo.StudentFinanceDetails", "StudentId");
            CreateIndex("dbo.StudentAssignment", "AssignmentId");
            CreateIndex("dbo.StudentAssignment", "StudentId");
            CreateIndex("dbo.Student", "SchoolId");
            CreateIndex("dbo.Student", "ClassId");
            CreateIndex("dbo.EmployeeFinanceDetails", "EmployeeId");
            CreateIndex("dbo.Designation", "SchoolId");
            CreateIndex("dbo.Employee", "SchoolId");
            CreateIndex("dbo.Employee", "DesignationId");
            CreateIndex("dbo.StudentDiary", "SchoolId");
            CreateIndex("dbo.StudentDiary", "InstructorId");
            CreateIndex("dbo.ClassStudentDiary", "ClassId");
            CreateIndex("dbo.ClassStudentDiary", "StudentDiaryId");
            CreateIndex("dbo.Class", "SchoolId");
            CreateIndex("dbo.ClassAssignement", "AssignmentId");
            CreateIndex("dbo.ClassAssignement", "ClassId");
            CreateIndex("dbo.Assignment", "SchoolId");
            CreateIndex("dbo.Assignment", "InstructorId");
            AddForeignKey("dbo.StudentAttendance", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.StudentAttendance", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.StudentAttendanceDetail", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.LessonPlan", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Assignment", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Class", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Course", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.CourseClass", "CourseId", "dbo.Course", "Id");
            AddForeignKey("dbo.CourseClass", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.StudentDiary", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Worksheet", "InstructorId", "dbo.Employee", "Id");
            AddForeignKey("dbo.Worksheet", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.TimeTableDetails", "TeacherId", "dbo.Employee", "Id");
            AddForeignKey("dbo.TimeTable", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Period", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.TimeTableDetails", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.TeacherDiary", "InstructorId", "dbo.Employee", "Id");
            AddForeignKey("dbo.TeacherDiary", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.ClassTeacherDiary", "TeacherDiaryId", "dbo.TeacherDiary", "Id");
            AddForeignKey("dbo.ClassTeacherDiary", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.StudentDiary", "InstructorId", "dbo.Employee", "Id");
            AddForeignKey("dbo.Employee", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.StudentStudentDiary", "StudentDiaryId", "dbo.StudentDiary", "Id");
            AddForeignKey("dbo.StudentStudentDiary", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.StudentFinanceDetails", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.StudentAssignment", "StudentId", "dbo.Student", "Id");
            AddForeignKey("dbo.StudentAssignment", "AssignmentId", "dbo.Assignment", "Id");
            AddForeignKey("dbo.Student", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Student", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.EmployeeFinanceDetails", "EmployeeId", "dbo.Employee", "Id");
            AddForeignKey("dbo.Designation", "SchoolId", "dbo.Schools", "Id");
            AddForeignKey("dbo.Employee", "DesignationId", "dbo.Designation", "Id");
            AddForeignKey("dbo.Assignment", "InstructorId", "dbo.Employee", "Id");
            AddForeignKey("dbo.ClassStudentDiary", "StudentDiaryId", "dbo.StudentDiary", "Id");
            AddForeignKey("dbo.ClassStudentDiary", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.ClassAssignement", "ClassId", "dbo.Class", "Id");
            AddForeignKey("dbo.ClassAssignement", "AssignmentId", "dbo.Assignment", "Id");
        }
    }
}
